spring:
  application:
    # 服务名称
    name: xframe-demo-consumer
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
      # 数据源
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            ruleType: flow


# 8090,8091。。.订单服务
server:
  port: 8090

feign:
  sentinel:
    enabled: true