# 此处代码仅做参考
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # 密码默认为空,没有则可以不填
    password: xx
    # 连接超时时长（毫秒）
    timeout: 6000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5
